import './globals.css'
import { Open_Sans } from 'next/font/google'
import Session from "./components/Session"
import Footer from './components/Footer'

const openSans = Open_Sans({ subsets: ['latin-ext', 'cyrillic-ext'], weight: ['500', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className} bg-general w-screen h-screen flex justify-center items-center text-white`}>
        <Footer />
        <Session>
          {children}
        </Session>
      </body>
    </html>
  )
}
